-- ============================================================
-- Migration: 002_stufe2_redesign.sql
-- Updates the responses.stage CHECK constraint for the
-- between-subjects redesign of Stufe 2.
--
-- Old values: 'stufe1', 'stufe2_block1', 'stufe2_block2', 'stufe2_depth'
-- New values: 'stufe1', 'stufe2_tasks'
--
-- Run this in the Supabase SQL Editor to apply to the live DB.
-- ============================================================

-- Drop the old constraint (name is auto-generated by Postgres
-- as "<table>_<column>_check" unless explicitly named)
ALTER TABLE responses DROP CONSTRAINT IF EXISTS responses_stage_check;

-- Add the updated constraint
ALTER TABLE responses ADD CONSTRAINT responses_stage_check
  CHECK (stage IN ('stufe1', 'stufe2_tasks'));
